// packages/vue/src/components/BarSparkline.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from "vue";
import { createTicker, seeded } from "@micrographics-js/core";

const props = withDefaults(defineProps<{ bars?: number; color?: string; height?: number; speed?: number; seed?: number }>(),
  { bars: 12, color: "var(--accent)", height: 32, speed: 200, seed: 7 });

const values = ref<number[]>(Array.from({ length: props.bars }, (_, i) => seeded(props.seed + i)));
let cleanup: (() => void) | null = null;
onMounted(() => { cleanup = createTicker(props.speed, () => { values.value = [...values.value.slice(1), Math.random()]; }); });
onUnmounted(() => cleanup?.());
const svgW = computed(() => props.bars * 4 - 1);
</script>
<template>
  <svg :width="svgW" :height="height" style="display:block" shape-rendering="crispEdges">
    <rect v-for="(v, i) in values" :key="i"
      :x="i * 4" :y="height - Math.max(1, Math.round(v * height))"
      width="3" :height="Math.max(1, Math.round(v * height))"
      :fill="color"
    />
  </svg>
</template>

// packages/svelte/src/components/BarSparkline.svelte
<script lang="ts">
import { createTicker, seeded } from "@micrographics-js/core";
let { bars = 12, color = "var(--accent)", height = 32, speed = 200, seed = 7 } = $props();
let values = $state(Array.from({length:bars}, (_,i) => seeded(seed+i)));
$effect(() => { return createTicker(speed, () => { values = [...values.slice(1), Math.random()]; }); });
const svgW = $derived(bars*4-1);
</script>
<svg width={svgW} {height} style="display:block" shape-rendering="crispEdges">
  {#each values as v, i}
    <rect x={i*4} y={height-Math.max(1,Math.round(v*height))} width="3" height={Math.max(1,Math.round(v*height))} fill={color}/>
  {/each}
</svg>
