// packages/react/src/components/BootSequence.tsx
"use client";
import { useEffect, useState } from "react";

export interface BootSequenceProps {
  delay?: number;
  color?: string;
}

export function BootSequence({ delay = 2000, color = "var(--accent)" }: BootSequenceProps) {
  const [ready, setReady] = useState(false);
  const [blink, setBlink] = useState(true);
  useEffect(() => {
    const t = setTimeout(() => setReady(true), delay);
    const id = setInterval(() => setBlink(v => !v), 400);
    return () => { clearTimeout(t); clearInterval(id); };
  }, [delay]);
  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, letterSpacing: "0.05em" }}>
      {ready
        ? "SYS·READY"
        : <span style={{ opacity: blink ? 1 : 0.4 }}>SYS·BOOTING</span>}
    </span>
  );
}

// packages/svelte/src/components/BootSequence.svelte
<script lang="ts">
let { delay = 2000, color = "var(--accent)" } = $props();
let ready = $state(false);
let blink = $state(true);
$effect(() => {
  const t = setTimeout(() => { ready = true; }, delay);
  const id = setInterval(() => { blink = !blink; }, 400);
  return () => { clearTimeout(t); clearInterval(id); };
});
</script>
<span style="font-family:monospace; font-size:11px; color:{color}; letter-spacing:0.05em">
  {#if ready}SYS·READY{:else}<span style="opacity:{blink ? 1 : 0.4}">SYS·BOOTING</span>{/if}
</span>
