// packages/react/src/components/FlowMeter.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics/core";

export interface FlowMeterProps {
  direction?: "right" | "left";
  speed?: number;
  color?: string;
  count?: number;
}

export function FlowMeter({ direction = "right", speed = 150, color = "var(--accent)", count = 5 }: FlowMeterProps) {
  const [offset, setOffset] = useState(0);
  useEffect(() =>
    createTicker(speed, () =>
      setOffset(o => (o + 1) % count)
    ), [speed, count]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "12px", color, letterSpacing: "0.05em" }}>
      {Array.from({ length: count }, (_, i) => (
        <span key={i} style={{ opacity: (i - offset + count) % count < 2 ? 1 : 0.25 }}>
          {direction === "right" ? ">" : "<"}
        </span>
      ))}
    </span>
  );
}

// packages/svelte/src/components/FlowMeter.svelte
<script lang="ts">
import { createTicker } from "@micrographics-js/core";
let { direction = "right" as "right" | "left", speed = 150, color = "var(--accent)", count = 5 } = $props();
let offset = $state(0);
$effect(() => {
  return createTicker(speed, () => { offset = (offset + 1) % count; });
});
const ch = $derived(direction === "right" ? ">" : "<");
</script>
<span style="font-family:monospace; font-size:12px; color:{color}; letter-spacing:0.05em">
  {#each Array.from({ length: count }, (_, i) => i) as i}
    <span style="opacity:{(i - offset + count) % count < 2 ? 1 : 0.25}">{ch}</span>
  {/each}
</span>
