// packages/react/src/components/FrequencyBars.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics/core";

export interface FrequencyBarsProps {
  bars?: number;
  color?: string;
  height?: number;
  speed?: number;
}

export function FrequencyBars({ bars = 8, color = "var(--accent)", height = 32, speed = 80 }: FrequencyBarsProps) {
  const [tick, setTick] = useState(0);
  useEffect(() => createTicker(speed, () => setTick(t => t + 1)), [speed]);

  const barW = 4;
  const gap = 2;
  const svgW = bars * (barW + gap) - gap;

  return (
    <svg width={svgW} height={height} style={{ display: "block" }} shapeRendering="crispEdges">
      {Array.from({ length: bars }, (_, i) => {
        const phase = (tick / 10 + i * 0.7) % (Math.PI * 2);
        const h = Math.max(2, Math.round(((Math.sin(phase) + 1) / 2) * height));
        return (
          <rect
            key={i}
            x={i * (barW + gap)}
            y={height - h}
            width={barW}
            height={h}
            fill={color}
          />
        );
      })}
    </svg>
  );
}

// packages/svelte/src/components/FrequencyBars.svelte
<script lang="ts">
import { createTicker } from "@micrographics/core";
let { bars = 8, color = "var(--accent)", height = 32, speed = 80 } = $props();
let tick = $state(0);
$effect(() => { return createTicker(speed, () => { tick++; }); });
const svgW = $derived(bars*6-2);
function barH(i: number) { return Math.max(2, Math.round(((Math.sin((tick/10+i*0.7)%(Math.PI*2))+1)/2)*height)); }
</script>
<svg width={svgW} {height} style="display:block" shape-rendering="crispEdges">
  {#each Array.from({length:bars},(_,i)=>i) as i}
    <rect x={i*6} y={height-barH(i)} width="4" height={barH(i)} fill={color}/>
  {/each}
</svg>
