// packages/react/src/components/GlitchText.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker, glitchText } from "@micrographics/core";

export interface GlitchTextProps {
  text?: string;
  intensity?: number;
  speed?: number;
  color?: string;
}

export function GlitchText({ text = "MICROGRAPHICS", intensity = 0.15, speed = 200, color = "var(--fg)" }: GlitchTextProps) {
  const [displayed, setDisplayed] = useState(text);
  useEffect(() =>
    createTicker(speed, () => {
      if (Math.random() < 0.3) {
        setDisplayed(glitchText(text, intensity));
        setTimeout(() => setDisplayed(text), 80);
      }
    }), [text, intensity, speed]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "12px", color, letterSpacing: "0.05em" }}>
      {displayed}
    </span>
  );
}

// packages/svelte/src/components/GlitchText.svelte
<script lang="ts">
import { createTicker, glitchText } from "@micrographics-js/core";
let { text = "MICROGRAPHICS", intensity = 0.15, speed = 200, color = "var(--fg)" } = $props();
let displayed = $state(text);

$effect(() => {
  displayed = text;
  return createTicker(speed, () => {
    if (Math.random() < 0.3) {
      displayed = glitchText(text, intensity);
      setTimeout(() => { displayed = text; }, 80);
    }
  });
});
</script>
<span style="font-family:monospace; font-size:12px; color:{color}; letter-spacing:0.05em">{displayed}</span>
