// packages/react/src/components/LogStream.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics-js/core";

const DEFAULT_ENTRIES = [
  "[INFO]  kernel: loaded modules ok",
  "[INFO]  net: interface eth0 up",
  "[WARN]  disk: usage at 87%",
  "[INFO]  svc: auth service started",
  "[INFO]  svc: api gateway ready",
  "[DEBUG] req: GET /health 200 2ms",
  "[INFO]  cron: job triggered",
  "[WARN]  mem: gc pressure detected",
  "[INFO]  sync: upstream ok",
  "[DEBUG] req: POST /event 201 8ms",
];

export interface LogStreamProps {
  entries?: string[];
  speed?: number;
  color?: string;
  maxLines?: number;
}

export function LogStream({ entries = DEFAULT_ENTRIES, speed = 800, color = "var(--fg-dim)", maxLines = 5 }: LogStreamProps) {
  const [lines, setLines] = useState<string[]>([]);
  const [idx, setIdx] = useState(0);

  useEffect(() =>
    createTicker(speed, () => {
      setLines(prev => [...prev.slice(-(maxLines - 1)), entries[idx % entries.length]]);
      setIdx(i => i + 1);
    }), [entries, speed, maxLines, idx]);

  return (
    <div style={{ fontFamily: "monospace", fontSize: "10px", color, lineHeight: "1.5", width: "200px", overflow: "hidden" }}>
      {lines.map((line, i) => (
        <div key={i} style={{ opacity: 0.5 + 0.5 * ((i + 1) / lines.length) }}>{line}</div>
      ))}
    </div>
  );
}

// packages/svelte/src/components/LogStream.svelte
<script lang="ts">
import { createTicker } from "@micrographics/core";
const DEFAULT_ENTRIES = [
  "[INFO]  kernel: loaded modules ok",
  "[INFO]  net: interface eth0 up",
  "[WARN]  disk: usage at 87%",
  "[INFO]  svc: auth service started",
  "[INFO]  svc: api gateway ready",
  "[DEBUG] req: GET /health 200 2ms",
  "[INFO]  cron: job triggered",
  "[WARN]  mem: gc pressure detected",
  "[INFO]  sync: upstream ok",
  "[DEBUG] req: POST /event 201 8ms",
];
let { entries = DEFAULT_ENTRIES, speed = 800, color = "var(--fg-dim)", maxLines = 5 } = $props();
let lines = $state<string[]>([]);
let idx = $state(0);

$effect(() => {
  return createTicker(speed, () => {
    lines = [...lines.slice(-(maxLines - 1)), entries[idx % entries.length]];
    idx = idx + 1;
  });
});
</script>
<div style="font-family:monospace; font-size:10px; color:{color}; line-height:1.5; width:200px; overflow:hidden">
  {#each lines as line, i}
    <div style="opacity:{0.5 + 0.5 * ((i + 1) / lines.length)}">{line}</div>
  {/each}
</div>
