// packages/vue/src/components/NumericStepper.vue
<script setup lang="ts">
import { ref, computed } from "vue";

const props = withDefaults(defineProps<{
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  color?: string;
}>(), { value: 0, min: 0, max: 999, step: 1, color: "var(--accent)" });

const emit = defineEmits<{ change: [value: number] }>();

const val = ref(props.value);

function decrement() {
  val.value = Math.max(props.min, val.value - props.step);
  emit("change", val.value);
}
function increment() {
  val.value = Math.min(props.max, val.value + props.step);
  emit("change", val.value);
}

const atMin = computed(() => val.value <= props.min);
const atMax = computed(() => val.value >= props.max);

function btnStyle(disabled: boolean) {
  return {
    fontFamily: 'monospace',
    fontSize: '11px',
    color: disabled ? 'var(--fg-dimmer)' : props.color,
    background: 'var(--bg-secondary)',
    border: `1px solid ${disabled ? 'var(--border)' : 'var(--border-strong)'}`,
    padding: '1px 5px',
    cursor: disabled ? 'default' : 'pointer',
    userSelect: 'none' as const,
    lineHeight: '1.4',
  };
}

const display = computed(() => String(val.value).padStart(3, "0"));
</script>
<template>
  <div :style="{ display: 'inline-flex', alignItems: 'center', gap: '0', fontFamily: 'monospace' }">
    <button :disabled="atMin" :style="btnStyle(atMin)" @click="decrement">&minus;</button>
    <span :style="{
      fontSize: '11px',
      color,
      padding: '1px 6px',
      background: 'var(--bg)',
      border: '1px solid var(--border)',
      borderLeft: 'none',
      borderRight: 'none',
      minWidth: '32px',
      textAlign: 'center',
      letterSpacing: '0.1em',
    }">{{ display }}</span>
    <button :disabled="atMax" :style="btnStyle(atMax)" @click="increment">+</button>
  </div>
</template>

// packages/svelte/src/components/NumericStepper.svelte
<script lang="ts">
let { value = 0, min = 0, max = 999, step = 1, onChange, color = "var(--accent)" }: { value?: number; min?: number; max?: number; step?: number; onChange?: (v: number) => void; color?: string } = $props();
let val = $state(value);
function decrement() {
  val = Math.max(min, val - step);
  onChange?.(val);
}
function increment() {
  val = Math.min(max, val + step);
  onChange?.(val);
}
const atMin = $derived(val <= min);
const atMax = $derived(val >= max);
const display = $derived(String(val).padStart(3, "0"));
</script>
<div style="display:inline-flex; align-items:center; gap:0; font-family:monospace">
  <button onclick={decrement} disabled={atMin} style="font-family:monospace; font-size:11px; color:{atMin ? 'var(--fg-dimmer)' : color}; background:var(--bg-secondary); border:1px solid {atMin ? 'var(--border)' : 'var(--border-strong)'}; padding:1px 5px; cursor:{atMin ? 'default' : 'pointer'}; user-select:none; line-height:1.4">&minus;</button>
  <span style="font-size:11px; color:{color}; padding:1px 6px; background:var(--bg); border:1px solid var(--border); border-left:none; border-right:none; min-width:32px; text-align:center; letter-spacing:0.1em">{display}</span>
  <button onclick={increment} disabled={atMax} style="font-family:monospace; font-size:11px; color:{atMax ? 'var(--fg-dimmer)' : color}; background:var(--bg-secondary); border:1px solid {atMax ? 'var(--border)' : 'var(--border-strong)'}; padding:1px 5px; cursor:{atMax ? 'default' : 'pointer'}; user-select:none; line-height:1.4">+</button>
</div>
