// packages/react/src/components/PanelTitle.tsx
export interface PanelTitleProps {
  title?: string;
  color?: string;
  accent?: string;
}

export function PanelTitle({ title = "PANEL", color = "var(--fg-dim)", accent = "var(--accent)" }: PanelTitleProps) {
  return (
    <div style={{ fontFamily: "monospace", fontSize: "10px", color, display: "flex", alignItems: "center", gap: "6px", userSelect: "none" }}>
      <span style={{ flex: 1, height: "1px", background: color, opacity: 0.4 }} />
      <span style={{ color: accent, letterSpacing: "0.15em" }}>{title}</span>
      <span style={{ flex: 1, height: "1px", background: color, opacity: 0.4 }} />
    </div>
  );
}

// packages/svelte/src/components/PanelTitle.svelte
<script lang="ts">
let { title = "PANEL", color = "var(--fg-dim)", accent = "var(--accent)" } = $props();
</script>
<div style="font-family:monospace; font-size:10px; color:{color}; display:flex; align-items:center; gap:6px; user-select:none">
  <span style="flex:1; height:1px; background:{color}; opacity:0.4"></span>
  <span style="color:{accent}; letter-spacing:0.15em">{title}</span>
  <span style="flex:1; height:1px; background:{color}; opacity:0.4"></span>
</div>
