// packages/react/src/components/PulseTag.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics-js/core";

export interface PulseTagProps {
  label?: string;
  color?: string;
  speed?: number;
}

export function PulseTag({ label = "LIVE", color = "var(--accent)", speed = 800 }: PulseTagProps) {
  const [on, setOn] = useState(true);
  useEffect(() => createTicker(speed, () => setOn(v => !v)), [speed]);
  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, display: "inline-flex", alignItems: "center", gap: "4px" }}>
      <span style={{ opacity: on ? 1 : 0, transition: "opacity 0.1s" }}>◆</span>
      <span>{label}</span>
    </span>
  );
}

// packages/svelte/src/components/PulseTag.svelte
<script lang="ts">
import { createTicker } from "@micrographics-js/core";
let { label = "LIVE", color = "var(--accent)", speed = 800 } = $props();
let on = $state(true);
$effect(() => { return createTicker(speed, () => { on = !on; }); });
</script>
<span style="font-family:monospace; font-size:11px; color:{color}; display:inline-flex; align-items:center; gap:4px">
  <span style="opacity:{on ? 1 : 0}; transition:opacity 0.1s">◆</span>
  <span>{label}</span>
</span>
