// packages/vue/src/components/RatingDots.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{ value?: number; max?: number; color?: string; emptyColor?: string }>(),
  { value: 3, max: 5, color: "var(--accent)", emptyColor: "var(--fg-dimmer)" });
</script>
<template>
  <span style="font-family:monospace; font-size:12px; letter-spacing:0.15em">
    <span v-for="i in max" :key="i" :style="{ color: i <= value ? props.color : props.emptyColor }">◆</span>
  </span>
</template>

// packages/svelte/src/components/RatingDots.svelte
<script lang="ts">
let { value = 3, max = 5, color = "var(--accent)", emptyColor = "var(--fg-dimmer)" } = $props();
</script>
<span style="font-family:monospace; font-size:12px; letter-spacing:0.15em">
  {#each Array.from({ length: max }, (_, i) => i) as i}
    <span style="color:{i < value ? color : emptyColor}">◆</span>
  {/each}
</span>
