// packages/vue/src/components/SystemLoad.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from "vue";
import { createTicker } from "@micrographics/core";

const props = withDefaults(defineProps<{
  cores?: number;
  width?: number;
  height?: number;
  color?: string;
  speed?: number;
}>(), { cores: 4, width: 60, height: 20, color: "var(--accent)", speed: 200 });

const loads = ref<number[]>(Array.from({ length: props.cores }, (_, i) => 0.3 + i * 0.1));

let cleanup: (() => void) | undefined;
onMounted(() => {
  cleanup = createTicker(props.speed, () => {
    loads.value = loads.value.map(v => {
      const delta = (Math.random() - 0.5) * 0.15;
      return Math.max(0.05, Math.min(0.98, v + delta));
    });
  });
});
onUnmounted(() => { cleanup?.(); });

const barH = computed(() => Math.floor((props.height - (props.cores - 1) * 1) / props.cores));

function barY(i: number) { return i * (barH.value + 1); }
function filled(v: number) { return Math.round(v * props.width); }
function barColor(v: number) {
  if (v > 0.8) return "var(--accent-red)";
  if (v > 0.6) return "var(--accent-amber)";
  return props.color;
}
</script>
<template>
  <svg :width="width" :height="height" style="display:block" shape-rendering="crispEdges">
    <g v-for="(v, i) in loads" :key="i">
      <rect :x="0" :y="barY(i)" :width="width" :height="barH" fill="var(--bg-secondary)" />
      <rect :x="0" :y="barY(i)" :width="filled(v)" :height="barH" :fill="barColor(v)" opacity="0.85" />
      <text :x="2" :y="barY(i) + barH - 1" fill="var(--bg)" font-size="5" font-family="monospace">C{{ i }}</text>
    </g>
  </svg>
</template>

// packages/svelte/src/components/SystemLoad.svelte
<script lang="ts">
import { createTicker } from "@micrographics-js/core";
let { cores = 4, width = 60, height = 20, color = "var(--accent)", speed = 200 } = $props();
let loads = $state(Array.from({ length: cores }, (_, i) => 0.3 + i * 0.1));
$effect(() => {
  return createTicker(speed, () => {
    loads = loads.map(v => {
      const delta = (Math.random() - 0.5) * 0.15;
      return Math.max(0.05, Math.min(0.98, v + delta));
    });
  });
});
const barH = $derived(Math.floor((height - (cores - 1) * 1) / cores));
</script>
<svg {width} {height} style="display:block" shape-rendering="crispEdges">
  {#each loads as v, i}
    {@const y = i * (barH + 1)}
    {@const filled = Math.round(v * width)}
    {@const barColor = v > 0.8 ? "var(--accent-red)" : v > 0.6 ? "var(--accent-amber)" : color}
    <rect x="0" {y} {width} height={barH} fill="var(--bg-secondary)" />
    <rect x="0" {y} width={filled} height={barH} fill={barColor} opacity="0.85" />
    <text x="2" y={y + barH - 1} fill="var(--bg)" font-size="5" font-family="monospace">C{i}</text>
  {/each}
</svg>
