// packages/svelte/src/components/ChevronRow.svelte
<script lang="ts">
import { createTicker } from "@micrographics/core";
let { direction = "right" as "right" | "left", color = "var(--fg-dimmer)", count = 6, speed = 200 } = $props();
let phase = $state(0);
$effect(() => { return createTicker(speed, () => { phase = (phase + 1) % count; }); });
const ch = $derived(direction === "right" ? ">" : "<");
</script>
<span style="font-family:monospace; font-size:12px; letter-spacing:0.05em">
  {#each Array.from({ length: count }, (_, i) => i) as i}
    {@const dist = direction === "right" ? (i - phase + count) % count : (phase - i + count) % count}
    <span style="color:{color}; opacity:{1 - dist * (0.8 / count)}">{ch}</span>
  {/each}
</span>

// packages/react/src/components/ChevronRow.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics/core";

export interface ChevronRowProps {
  direction?: "right" | "left";
  color?: string;
  count?: number;
  speed?: number;
}

export function ChevronRow({ direction = "right", color = "var(--fg-dimmer)", count = 6, speed = 200 }: ChevronRowProps) {
  const [phase, setPhase] = useState(0);
  useEffect(() => createTicker(speed, () => setPhase(p => (p + 1) % count)), [speed, count]);

  const ch = direction === "right" ? ">" : "<";
  return (
    <span style={{ fontFamily: "monospace", fontSize: "12px", letterSpacing: "0.05em" }}>
      {Array.from({ length: count }, (_, i) => {
        const dist = direction === "right"
          ? (i - phase + count) % count
          : (phase - i + count) % count;
        return (
          <span key={i} style={{ color, opacity: 1 - dist * (0.8 / count) }}>{ch}</span>
        );
      })}
    </span>
  );
}
