// packages/vue/src/components/CopyButton.vue
<script setup lang="ts">
import { ref } from "vue";

const props = withDefaults(defineProps<{ text?: string; color?: string }>(), { text: "copy me", color: "var(--fg-dim)" });
const copied = ref(false);
const handleClick = () => {
  navigator.clipboard?.writeText(props.text).catch(() => {});
  copied.value = true;
  setTimeout(() => { copied.value = false; }, 2000);
};
</script>
<template>
  <button @click="handleClick" :style="{ fontFamily: 'monospace', fontSize: '10px', color: copied ? 'var(--accent)' : props.color, background: 'none', border: `1px solid ${copied ? 'var(--accent)' : props.color}`, padding: '2px 6px', cursor: 'pointer', letterSpacing: '0.05em', transition: 'color 0.1s, border-color 0.1s' }">
    {{ copied ? '[COPIED ✓]' : '[COPY]' }}
  </button>
</template>

// packages/react/src/components/CopyButton.tsx
"use client";
import { useState } from "react";

export interface CopyButtonProps {
  text?: string;
  color?: string;
}

export function CopyButton({ text = "copy me", color = "var(--fg-dim)" }: CopyButtonProps) {
  const [state, setState] = useState<"idle" | "copied">("idle");

  const handleClick = () => {
    navigator.clipboard?.writeText(text).catch(() => {});
    setState("copied");
    setTimeout(() => setState("idle"), 2000);
  };

  return (
    <button
      onClick={handleClick}
      style={{
        fontFamily: "monospace",
        fontSize: "10px",
        color: state === "copied" ? "var(--accent)" : color,
        background: "none",
        border: `1px solid ${state === "copied" ? "var(--accent)" : color}`,
        padding: "2px 6px",
        cursor: "pointer",
        letterSpacing: "0.05em",
        transition: "color 0.1s, border-color 0.1s",
      }}
    >
      {state === "copied" ? "[COPIED ✓]" : "[COPY]"}
    </button>
  );
}
