// packages/svelte/src/components/ErrorRate.svelte
<script lang="ts">
import { createTicker } from "@micrographics-js/core";
let { count = 7, speed = 1500 } = $props();
let on = $state(true), current = $state(count);
$effect(() => {
  return createTicker(speed, () => { on = !on; if (Math.random()<0.3) current++; });
});
</script>
<span style="font-family:monospace; font-size:11px; color:var(--accent-red); opacity:{on ? 1 : 0.4}; transition:opacity 0.1s">ERR:{current}</span>

// packages/react/src/components/ErrorRate.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics-js/core";

export interface ErrorRateProps {
  count?: number;
  speed?: number;
}

export function ErrorRate({ count = 7, speed = 1500 }: ErrorRateProps) {
  const [on, setOn] = useState(true);
  const [current, setCurrent] = useState(count);
  useEffect(() => {
    const t = createTicker(speed, () => {
      setOn(v => !v);
      if (Math.random() < 0.3) setCurrent(c => c + 1);
    });
    return t;
  }, [speed, count]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color: "var(--accent-red)", opacity: on ? 1 : 0.4, transition: "opacity 0.1s" }}>
      ERR:{current}
    </span>
  );
}
