// packages/vue/src/components/FlowMeter.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { createTicker } from "@micrographics/core";

const props = withDefaults(defineProps<{ direction?: string; speed?: number; color?: string; count?: number }>(),
  { direction: "right", speed: 150, color: "var(--accent)", count: 5 });

const offset = ref(0);
let cleanup: (() => void) | null = null;
onMounted(() => { cleanup = createTicker(props.speed, () => { offset.value = (offset.value + 1) % props.count; }); });
onUnmounted(() => cleanup?.());
const opacity = (i: number) => (i - offset.value + props.count) % props.count < 2 ? 1 : 0.25;
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '12px', color: props.color, letterSpacing: '0.05em' }">
    <span v-for="i in count" :key="i" :style="{ opacity: opacity(i-1) }">{{ props.direction === 'right' ? '>' : '<' }}</span>
  </span>
</template>

// packages/react/src/components/FlowMeter.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics/core";

export interface FlowMeterProps {
  direction?: "right" | "left";
  speed?: number;
  color?: string;
  count?: number;
}

export function FlowMeter({ direction = "right", speed = 150, color = "var(--accent)", count = 5 }: FlowMeterProps) {
  const [offset, setOffset] = useState(0);
  useEffect(() =>
    createTicker(speed, () =>
      setOffset(o => (o + 1) % count)
    ), [speed, count]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "12px", color, letterSpacing: "0.05em" }}>
      {Array.from({ length: count }, (_, i) => (
        <span key={i} style={{ opacity: (i - offset + count) % count < 2 ? 1 : 0.25 }}>
          {direction === "right" ? ">" : "<"}
        </span>
      ))}
    </span>
  );
}
