// packages/vue/src/components/PulseTag.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { createTicker } from "@micrographics-js/core";

const props = withDefaults(defineProps<{ label?: string; color?: string; speed?: number }>(),
  { label: "LIVE", color: "var(--accent)", speed: 800 });

const on = ref(true);
let cleanup: (() => void) | null = null;
onMounted(() => { cleanup = createTicker(props.speed, () => { on.value = !on.value; }); });
onUnmounted(() => cleanup?.());
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color, display: 'inline-flex', alignItems: 'center', gap: '4px' }">
    <span :style="{ opacity: on ? 1 : 0, transition: 'opacity 0.1s' }">◆</span>
    <span>{{ props.label }}</span>
  </span>
</template>

// packages/react/src/components/PulseTag.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics-js/core";

export interface PulseTagProps {
  label?: string;
  color?: string;
  speed?: number;
}

export function PulseTag({ label = "LIVE", color = "var(--accent)", speed = 800 }: PulseTagProps) {
  const [on, setOn] = useState(true);
  useEffect(() => createTicker(speed, () => setOn(v => !v)), [speed]);
  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, display: "inline-flex", alignItems: "center", gap: "4px" }}>
      <span style={{ opacity: on ? 1 : 0, transition: "opacity 0.1s" }}>◆</span>
      <span>{label}</span>
    </span>
  );
}
