// packages/svelte/src/components/RatingDots.svelte
<script lang="ts">
let { value = 3, max = 5, color = "var(--accent)", emptyColor = "var(--fg-dimmer)" } = $props();
</script>
<span style="font-family:monospace; font-size:12px; letter-spacing:0.15em">
  {#each Array.from({ length: max }, (_, i) => i) as i}
    <span style="color:{i < value ? color : emptyColor}">◆</span>
  {/each}
</span>

// packages/react/src/components/RatingDots.tsx
export interface RatingDotsProps {
  value?: number;
  max?: number;
  color?: string;
  emptyColor?: string;
}

export function RatingDots({ value = 3, max = 5, color = "var(--accent)", emptyColor = "var(--fg-dimmer)" }: RatingDotsProps) {
  return (
    <span style={{ fontFamily: "monospace", fontSize: "12px", letterSpacing: "0.15em" }}>
      {Array.from({ length: max }, (_, i) => (
        <span key={i} style={{ color: i < value ? color : emptyColor }}>◆</span>
      ))}
    </span>
  );
}
