// packages/svelte/src/components/SignalQuality.svelte
<script lang="ts">
let { quality = 3, width = 24, height = 16, color = "var(--accent)" } = $props();
const bars = 5;
const barW = $derived(Math.floor((width - (bars - 1) * 2) / bars));
const clampedQ = $derived(Math.max(0, Math.min(bars, quality)));
</script>
<svg {width} {height} style="display:block" shape-rendering="crispEdges">
  {#each Array.from({ length: bars }) as _, i}
    {@const barH = Math.round(height * (0.2 + (i / (bars - 1)) * 0.8))}
    {@const x = i * (barW + 2)}
    {@const y = height - barH}
    {@const active = i < clampedQ}
    <rect {x} {y} width={barW} height={barH} fill={active ? color : "var(--fg-dimmer)"} opacity={active ? 0.9 : 0.2} />
  {/each}
</svg>

// packages/react/src/components/SignalQuality.tsx
"use client";

export interface SignalQualityProps {
  quality?: number;
  width?: number;
  height?: number;
  color?: string;
}

export function SignalQuality({ quality = 3, width = 24, height = 16, color = "var(--accent)" }: SignalQualityProps) {
  const bars = 5;
  const barW = Math.floor((width - (bars - 1) * 2) / bars);
  const clampedQ = Math.max(0, Math.min(bars, quality));

  return (
    <svg width={width} height={height} style={{ display: "block" }} shapeRendering="crispEdges">
      {Array.from({ length: bars }, (_, i) => {
        const barH = Math.round(height * (0.2 + (i / (bars - 1)) * 0.8));
        const x = i * (barW + 2);
        const y = height - barH;
        const active = i < clampedQ;
        return (
          <rect
            key={i}
            x={x}
            y={y}
            width={barW}
            height={barH}
            fill={active ? color : "var(--fg-dimmer)"}
            opacity={active ? 0.9 : 0.2}
          />
        );
      })}
    </svg>
  );
}
