// packages/vue/src/components/StopwatchDisplay.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{
  running?: boolean;
  color?: string;
}>(), { running: false, color: "var(--accent)" });

const elapsed = ref(0);
let startTime: number | null = null;
let accumulated = 0;
let rafId = 0;

function tick() {
  if (startTime !== null) {
    elapsed.value = accumulated + (performance.now() - startTime);
  }
  rafId = requestAnimationFrame(tick);
}

function startTimer() {
  startTime = performance.now();
  rafId = requestAnimationFrame(tick);
}

function stopTimer() {
  if (startTime !== null) {
    accumulated += performance.now() - startTime;
    startTime = null;
  }
  cancelAnimationFrame(rafId);
}

onMounted(() => { if (props.running) startTimer(); });
onUnmounted(() => { cancelAnimationFrame(rafId); });

watch(() => props.running, (val) => {
  if (val) startTimer();
  else stopTimer();
});

const pad2 = (n: number) => String(n).padStart(2, "0");
const hours = computed(() => Math.floor(Math.floor(elapsed.value / 1000) / 3600));
const mins = computed(() => Math.floor((Math.floor(elapsed.value / 1000) % 3600) / 60));
const secs = computed(() => Math.floor(elapsed.value / 1000) % 60);
const millis = computed(() => Math.floor((elapsed.value % 1000) / 10));
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '13px', color, letterSpacing: '0.06em' }">
    {{ pad2(hours) }}:{{ pad2(mins) }}:{{ pad2(secs) }}<span :style="{ fontSize: '10px', color: 'var(--fg-dim)', marginLeft: '1px' }">:{{ pad2(millis) }}</span>
  </span>
</template>

// packages/react/src/components/StopwatchDisplay.tsx
"use client";
import { useEffect, useRef, useState } from "react";

export interface StopwatchDisplayProps {
  running?: boolean;
  color?: string;
}

export function StopwatchDisplay({ running = false, color = "var(--accent)" }: StopwatchDisplayProps) {
  const [elapsed, setElapsed] = useState(0);
  const startRef = useRef<number | null>(null);
  const rafRef = useRef<number>(0);
  const accRef = useRef(0);

  useEffect(() => {
    if (running) {
      startRef.current = performance.now();
      const tick = () => {
        if (startRef.current !== null) {
          setElapsed(accRef.current + (performance.now() - startRef.current));
        }
        rafRef.current = requestAnimationFrame(tick);
      };
      rafRef.current = requestAnimationFrame(tick);
    } else {
      if (startRef.current !== null) {
        accRef.current += performance.now() - startRef.current;
        startRef.current = null;
      }
      cancelAnimationFrame(rafRef.current);
    }
    return () => cancelAnimationFrame(rafRef.current);
  }, [running]);

  const ms = elapsed;
  const totalSecs = Math.floor(ms / 1000);
  const hours = Math.floor(totalSecs / 3600);
  const mins = Math.floor((totalSecs % 3600) / 60);
  const secs = totalSecs % 60;
  const millis = Math.floor((ms % 1000) / 10);

  const pad2 = (n: number) => String(n).padStart(2, "0");

  return (
    <span style={{ fontFamily: "monospace", fontSize: "13px", color, letterSpacing: "0.06em" }}>
      {pad2(hours)}:{pad2(mins)}:{pad2(secs)}
      <span style={{ fontSize: "10px", color: "var(--fg-dim)", marginLeft: "1px" }}>:{pad2(millis)}</span>
    </span>
  );
}
