// packages/vue/src/components/UnixTimestamp.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{ color?: string }>(), { color: "var(--fg-dim)" });
const ts = ref(Math.floor(Date.now() / 1000));
let id: ReturnType<typeof setInterval> | null = null;
onMounted(() => { id = setInterval(() => { ts.value = Math.floor(Date.now() / 1000); }, 1000); });
onUnmounted(() => { if (id) clearInterval(id); });
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color, letterSpacing: '0.05em' }">{{ ts }}</span>
</template>

// packages/react/src/components/UnixTimestamp.tsx
"use client";
import { useEffect, useState } from "react";

export interface UnixTimestampProps {
  color?: string;
}

export function UnixTimestamp({ color = "var(--fg-dim)" }: UnixTimestampProps) {
  const [ts, setTs] = useState(Math.floor(Date.now() / 1000));
  useEffect(() => {
    const id = setInterval(() => setTs(Math.floor(Date.now() / 1000)), 1000);
    return () => clearInterval(id);
  }, []);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, letterSpacing: "0.05em" }}>
      {ts}
    </span>
  );
}
