// packages/react/src/components/BootSequence.tsx
"use client";
import { useEffect, useState } from "react";

export interface BootSequenceProps {
  delay?: number;
  color?: string;
}

export function BootSequence({ delay = 2000, color = "var(--accent)" }: BootSequenceProps) {
  const [ready, setReady] = useState(false);
  const [blink, setBlink] = useState(true);
  useEffect(() => {
    const t = setTimeout(() => setReady(true), delay);
    const id = setInterval(() => setBlink(v => !v), 400);
    return () => { clearTimeout(t); clearInterval(id); };
  }, [delay]);
  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, letterSpacing: "0.05em" }}>
      {ready
        ? "SYS·READY"
        : <span style={{ opacity: blink ? 1 : 0.4 }}>SYS·BOOTING</span>}
    </span>
  );
}

// packages/vue/src/components/BootSequence.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{ delay?: number; color?: string }>(), { delay: 2000, color: "var(--accent)" });
const ready = ref(false);
const blink = ref(true);
let t: ReturnType<typeof setTimeout> | null = null;
let id: ReturnType<typeof setInterval> | null = null;
onMounted(() => {
  t = setTimeout(() => { ready.value = true; }, props.delay);
  id = setInterval(() => { blink.value = !blink.value; }, 400);
});
onUnmounted(() => { if (t) clearTimeout(t); if (id) clearInterval(id); });
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color, letterSpacing: '0.05em' }">
    <span v-if="ready">SYS·READY</span>
    <span v-else :style="{ opacity: blink ? 1 : 0.4 }">SYS·BOOTING</span>
  </span>
</template>
