// packages/react/src/components/CounterUp.tsx
"use client";
import { useEffect, useState } from "react";

export interface CounterUpProps {
  target?: number;
  duration?: number;
  color?: string;
  prefix?: string;
  suffix?: string;
}

export function CounterUp({ target = 1337, duration = 1500, color = "var(--fg)", prefix = "", suffix = "" }: CounterUpProps) {
  const [value, setValue] = useState(0);
  useEffect(() => {
    const start = Date.now();
    const tick = () => {
      const elapsed = Date.now() - start;
      const progress = Math.min(elapsed / duration, 1);
      setValue(Math.round(progress * target));
      if (progress < 1) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  }, [target, duration]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "14px", color, letterSpacing: "0.05em" }}>
      {prefix}{value.toLocaleString()}{suffix}
    </span>
  );
}

// packages/vue/src/components/CounterUp.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

const props = withDefaults(defineProps<{ target?: number; duration?: number; color?: string; prefix?: string; suffix?: string }>(),
  { target: 1337, duration: 1500, color: "var(--fg)", prefix: "", suffix: "" });

const value = ref(0);
onMounted(() => {
  const start = Date.now();
  const tick = () => {
    const progress = Math.min((Date.now() - start) / props.duration, 1);
    value.value = Math.round(progress * props.target);
    if (progress < 1) requestAnimationFrame(tick);
  };
  requestAnimationFrame(tick);
});
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '14px', color: props.color, letterSpacing: '0.05em' }">
    {{ props.prefix }}{{ value.toLocaleString() }}{{ props.suffix }}
  </span>
</template>
