// packages/svelte/src/components/CounterUp.svelte
<script lang="ts">
let { target = 1337, duration = 1500, color = "var(--fg)", prefix = "", suffix = "" } = $props();
let value = $state(0);

$effect(() => {
  value = 0;
  const start = Date.now();
  const tick = () => {
    const elapsed = Date.now() - start;
    const progress = Math.min(elapsed / duration, 1);
    value = Math.round(progress * target);
    if (progress < 1) requestAnimationFrame(tick);
  };
  requestAnimationFrame(tick);
});
</script>
<span style="font-family:monospace; font-size:14px; color:{color}; letter-spacing:0.05em">{prefix}{value.toLocaleString()}{suffix}</span>

// packages/vue/src/components/CounterUp.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

const props = withDefaults(defineProps<{ target?: number; duration?: number; color?: string; prefix?: string; suffix?: string }>(),
  { target: 1337, duration: 1500, color: "var(--fg)", prefix: "", suffix: "" });

const value = ref(0);
onMounted(() => {
  const start = Date.now();
  const tick = () => {
    const progress = Math.min((Date.now() - start) / props.duration, 1);
    value.value = Math.round(progress * props.target);
    if (progress < 1) requestAnimationFrame(tick);
  };
  requestAnimationFrame(tick);
});
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '14px', color: props.color, letterSpacing: '0.05em' }">
    {{ props.prefix }}{{ value.toLocaleString() }}{{ props.suffix }}
  </span>
</template>
