// packages/react/src/components/HexDump.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker, seeded } from "@micrographics/core";

export interface HexDumpProps {
  rows?: number;
  cols?: number;
  speed?: number;
  color?: string;
  seed?: number;
}

export function HexDump({ rows = 4, cols = 8, speed = 200, color = "var(--fg-dimmer)", seed = 42 }: HexDumpProps) {
  const [cells, setCells] = useState<string[][]>(() =>
    Array.from({ length: rows }, (_, ri) =>
      Array.from({ length: cols }, (_, ci) =>
        Math.floor(seeded(seed + ri * cols + ci) * 256).toString(16).toUpperCase().padStart(2, "0"),
      ),
    ),
  );
  const [flashCell, setFlashCell] = useState<[number, number] | null>(null);

  useEffect(() =>
    createTicker(speed, () => {
      const r = Math.floor(Math.random() * rows);
      const c = Math.floor(Math.random() * cols);
      const val = Math.floor(Math.random() * 256).toString(16).toUpperCase().padStart(2, "0");
      setCells(prev => {
        const next = prev.map(row => [...row]);
        next[r][c] = val;
        return next;
      });
      setFlashCell([r, c]);
      setTimeout(() => setFlashCell(null), 150);
    }), [rows, cols, speed]);

  return (
    <div style={{ fontFamily: "monospace", fontSize: "10px", color, lineHeight: "1.6" }}>
      {cells.map((row, ri) => (
        <div key={ri} style={{ display: "flex", gap: "4px" }}>
          <span style={{ color: "var(--fg-dimmer)", opacity: 0.5 }}>
            {(ri * cols).toString(16).toUpperCase().padStart(4, "0")}:
          </span>
          {row.map((cell, ci) => (
            <span
              key={ci}
              style={{
                color: flashCell?.[0] === ri && flashCell?.[1] === ci ? "var(--accent)" : color,
                transition: "color 0.1s",
              }}
            >
              {cell}
            </span>
          ))}
        </div>
      ))}
    </div>
  );
}

// packages/vue/src/components/HexDump.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { createTicker, seeded } from "@micrographics/core";

const props = withDefaults(defineProps<{ rows?: number; cols?: number; speed?: number; color?: string; seed?: number }>(),
  { rows: 4, cols: 8, speed: 200, color: "var(--fg-dimmer)", seed: 42 });

const cells = ref<string[][]>(Array.from({ length: props.rows }, (_, ri) =>
  Array.from({ length: props.cols }, (_, ci) => Math.floor(seeded(props.seed + ri * props.cols + ci) * 256).toString(16).toUpperCase().padStart(2, "0"))
));
const flashCell = ref<[number, number] | null>(null);
let cleanup: (() => void) | null = null;
onMounted(() => {
  cleanup = createTicker(props.speed, () => {
    const r = Math.floor(Math.random() * props.rows);
    const c = Math.floor(Math.random() * props.cols);
    const next = cells.value.map(row => [...row]);
    next[r][c] = Math.floor(Math.random() * 256).toString(16).toUpperCase().padStart(2, "0");
    cells.value = next;
    flashCell.value = [r, c];
    setTimeout(() => { flashCell.value = null; }, 150);
  });
});
onUnmounted(() => cleanup?.());
const isFlash = (r: number, c: number) => flashCell.value?.[0] === r && flashCell.value?.[1] === c;
</script>
<template>
  <div :style="{ fontFamily: 'monospace', fontSize: '10px', color: props.color, lineHeight: '1.6' }">
    <div v-for="(row, ri) in cells" :key="ri" style="display:flex; gap:4px">
      <span style="color:var(--fg-dimmer); opacity:0.5">{{ (ri * props.cols).toString(16).toUpperCase().padStart(4, '0') }}:</span>
      <span v-for="(cell, ci) in row" :key="ci"
        :style="{ color: isFlash(ri, ci) ? 'var(--accent)' : props.color, transition: 'color 0.1s' }">
        {{ cell }}
      </span>
    </div>
  </div>
</template>
