// packages/svelte/src/components/MemoryBar.svelte
<script lang="ts">
let { used = 6.4, total = 16, unit = "GB", segments = 10, color = "var(--accent)", width = 80, height = 8 } = $props();
const pct = $derived(used / total);
const filled = $derived(Math.round(pct * segments));
const segW = $derived(Math.floor(width / segments) - 1);
const barColor = $derived(pct > 0.85 ? "var(--accent-red)" : pct > 0.65 ? "var(--accent-amber)" : color);
</script>
<div style="display:flex; flex-direction:column; gap:2px">
  <svg {width} {height} style="display:block" shape-rendering="crispEdges">
    {#each Array.from({length:segments},(_,i)=>i) as i}
      <rect x={i*(segW+1)} y="0" width={segW} {height}
        fill={i < filled ? barColor : "var(--fg-dimmer)"} opacity={i < filled ? 1 : 0.2}/>
    {/each}
  </svg>
  <span style="font-family:monospace; font-size:9px; color:var(--fg-dimmer)">{used}{unit} / {total}{unit}</span>
</div>

// packages/vue/src/components/MemoryBar.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(defineProps<{ used?: number; total?: number; unit?: string; segments?: number; color?: string; width?: number; height?: number }>(),
  { used: 6.4, total: 16, unit: "GB", segments: 10, color: "var(--accent)", width: 80, height: 8 });

const pct = computed(() => props.used / props.total);
const filled = computed(() => Math.round(pct.value * props.segments));
const segW = computed(() => Math.floor(props.width / props.segments) - 1);
const barColor = computed(() => pct.value > 0.85 ? "var(--accent-red)" : pct.value > 0.65 ? "var(--accent-amber)" : props.color);
</script>
<template>
  <div style="display:flex; flex-direction:column; gap:2px">
    <svg :width="width" :height="height" style="display:block" shape-rendering="crispEdges">
      <rect v-for="i in segments" :key="i"
        :x="(i-1) * (segW + 1)" y="0" :width="segW" :height="height"
        :fill="i <= filled ? barColor : 'var(--fg-dimmer)'"
        :opacity="i <= filled ? 1 : 0.2"
      />
    </svg>
    <span style="font-family:monospace; font-size:9px; color:var(--fg-dimmer)">{{ props.used }}{{ props.unit }} / {{ props.total }}{{ props.unit }}</span>
  </div>
</template>
