// packages/react/src/components/PingIndicator.tsx
"use client";
import { useEffect, useState } from "react";
import { createTicker } from "@micrographics/core";

export interface PingIndicatorProps {
  ms?: number;
  color?: string;
  speed?: number;
}

export function PingIndicator({ ms = 42, color = "var(--accent)", speed = 2000 }: PingIndicatorProps) {
  const [active, setActive] = useState(false);
  useEffect(() =>
    createTicker(speed, () => {
      setActive(true);
      setTimeout(() => setActive(false), 200);
    }), [speed]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, display: "inline-flex", alignItems: "center", gap: "5px" }}>
      <span style={{
        display: "inline-block",
        width: "6px",
        height: "6px",
        background: active ? color : "transparent",
        border: `1px solid ${color}`,
        borderRadius: "0",
        transition: "background 0.1s",
      }} />
      {ms}ms
    </span>
  );
}

// packages/vue/src/components/PingIndicator.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { createTicker } from "@micrographics/core";

const props = withDefaults(defineProps<{ ms?: number; color?: string; speed?: number }>(),
  { ms: 42, color: "var(--accent)", speed: 2000 });

const active = ref(false);
let cleanup: (() => void) | null = null;
onMounted(() => {
  cleanup = createTicker(props.speed, () => { active.value = true; setTimeout(() => { active.value = false; }, 200); });
});
onUnmounted(() => cleanup?.());
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color, display: 'inline-flex', alignItems: 'center', gap: '5px' }">
    <span :style="{ display: 'inline-block', width: '6px', height: '6px', background: active ? props.color : 'transparent', border: `1px solid ${props.color}`, transition: 'background 0.1s' }" />
    {{ props.ms }}ms
  </span>
</template>
