// packages/react/src/components/ReadyBadge.tsx
"use client";
import { useEffect, useState } from "react";

export interface ReadyBadgeProps {
  color?: string;
  delay?: number;
}

const SEGMENTS = ["[", " ", "R", "E", "A", "D", "Y", " ", "]"];

export function ReadyBadge({ color = "var(--accent)", delay = 80 }: ReadyBadgeProps) {
  const [visible, setVisible] = useState(0);
  useEffect(() => {
    setVisible(0);
    const ids = SEGMENTS.map((_, i) => setTimeout(() => setVisible(i + 1), delay * (i + 1)));
    return () => ids.forEach(clearTimeout);
  }, [delay]);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "12px", color, letterSpacing: "0.05em" }}>
      {SEGMENTS.slice(0, visible).join("")}
    </span>
  );
}

// packages/vue/src/components/ReadyBadge.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{ color?: string; delay?: number }>(), { color: "var(--accent)", delay: 80 });
const SEGMENTS = ["[", " ", "R", "E", "A", "D", "Y", " ", "]"];
const visible = ref(0);
const timeouts: ReturnType<typeof setTimeout>[] = [];
onMounted(() => {
  visible.value = 0;
  SEGMENTS.forEach((_, i) => timeouts.push(setTimeout(() => { visible.value = i + 1; }, props.delay * (i + 1))));
});
onUnmounted(() => timeouts.forEach(clearTimeout));
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '12px', color: props.color, letterSpacing: '0.05em' }">
    {{ SEGMENTS.slice(0, visible).join("") }}
  </span>
</template>
