// packages/svelte/src/components/SegmentedBar.svelte
<script lang="ts">
let { value = 60, segments = 10, width = 80, height = 8, color = "var(--accent)", showLabel = false } = $props();
const filled = $derived(Math.round((value / 100) * segments));
const segW = $derived(Math.floor((width - (segments - 1)) / segments));
const totalW = $derived(segments * segW + (segments - 1));
</script>
<div style="display:inline-flex; flex-direction:column; gap:2px">
  <svg width={totalW} {height} style="display:block" shape-rendering="crispEdges">
    {#each Array.from({ length: segments }) as _, i}
      <rect x={i * (segW + 1)} y="0" width={segW} {height} fill={i < filled ? color : "var(--fg-dimmer)"} opacity={i < filled ? 0.9 : 0.2} />
    {/each}
  </svg>
  {#if showLabel}
    <span style="font-family:monospace; font-size:8px; color:var(--fg-dim); text-align:right">{value}%</span>
  {/if}
</div>

// packages/vue/src/components/SegmentedBar.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(defineProps<{
  value?: number;
  segments?: number;
  width?: number;
  height?: number;
  color?: string;
  showLabel?: boolean;
}>(), { value: 60, segments: 10, width: 80, height: 8, color: "var(--accent)", showLabel: false });

const filled = computed(() => Math.round((props.value / 100) * props.segments));
const segW = computed(() => Math.floor((props.width - (props.segments - 1)) / props.segments));
const totalW = computed(() => props.segments * segW.value + (props.segments - 1));
</script>
<template>
  <div :style="{ display: 'inline-flex', flexDirection: 'column', gap: '2px' }">
    <svg :width="totalW" :height="height" style="display:block" shape-rendering="crispEdges">
      <rect
        v-for="i in segments" :key="i"
        :x="(i - 1) * (segW + 1)"
        :y="0"
        :width="segW"
        :height="height"
        :fill="(i - 1) < filled ? color : 'var(--fg-dimmer)'"
        :opacity="(i - 1) < filled ? 0.9 : 0.2"
      />
    </svg>
    <span v-if="showLabel" :style="{ fontFamily: 'monospace', fontSize: '8px', color: 'var(--fg-dim)', textAlign: 'right' }">{{ value }}%</span>
  </div>
</template>
