// packages/react/src/components/Typewriter.tsx
"use client";
import { useEffect, useState } from "react";

export interface TypewriterProps {
  text?: string;
  speed?: number;
  color?: string;
  loop?: boolean;
}

export function Typewriter({ text = "SYSTEM·ONLINE", speed = 50, color = "var(--fg)", loop = true }: TypewriterProps) {
  const [displayed, setDisplayed] = useState("");
  const [cursor, setCursor] = useState(true);

  useEffect(() => {
    let cancelled = false;
    let i = 0;
    setDisplayed("");

    const tick = () => {
      if (cancelled) return;
      i++;
      setDisplayed(text.slice(0, i));
      if (i < text.length) {
        setTimeout(tick, speed);
      } else if (loop) {
        setTimeout(() => {
          if (!cancelled) { i = 0; setDisplayed(""); setTimeout(tick, speed); }
        }, 1500);
      }
    };
    setTimeout(tick, speed);
    return () => { cancelled = true; };
  }, [text, speed, loop]);

  useEffect(() => {
    const id = setInterval(() => setCursor(v => !v), 530);
    return () => clearInterval(id);
  }, []);

  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color }}>
      {displayed}
      <span style={{ opacity: cursor ? 1 : 0 }}>█</span>
    </span>
  );
}

// packages/vue/src/components/Typewriter.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{ text?: string; speed?: number; color?: string; loop?: boolean }>(),
  { text: "SYSTEM·ONLINE", speed: 50, color: "var(--fg)", loop: true });

const displayed = ref("");
const cursor = ref(true);
let cancelled = false;
let cursorId: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
  cancelled = false;
  cursorId = setInterval(() => { cursor.value = !cursor.value; }, 530);
  const run = async () => {
    let i = 0; displayed.value = "";
    while (!cancelled) {
      i++; displayed.value = props.text.slice(0, i);
      if (i >= props.text.length) {
        if (!props.loop) break;
        await new Promise<void>(r => setTimeout(r, 1500));
        if (cancelled) break;
        i = 0; displayed.value = "";
      }
      await new Promise<void>(r => setTimeout(r, props.speed));
    }
  };
  run();
});
onUnmounted(() => { cancelled = true; if (cursorId) clearInterval(cursorId); });
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color }">
    {{ displayed }}<span :style="{ opacity: cursor ? 1 : 0 }">█</span>
  </span>
</template>
