// packages/react/src/components/Uptime.tsx
"use client";
import { useEffect, useState } from "react";

export interface UptimeProps {
  startMs?: number;
  color?: string;
}

function format(ms: number): string {
  const s = Math.floor(ms / 1000);
  const days = Math.floor(s / 86400);
  const hours = Math.floor((s % 86400) / 3600);
  const mins = Math.floor((s % 3600) / 60);
  const secs = s % 60;
  return `${String(days).padStart(2, "0")}:${String(hours).padStart(2, "0")}:${String(mins).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
}

const MOUNT_TIME = Date.now();

export function Uptime({ startMs, color = "var(--fg)" }: UptimeProps) {
  const start = startMs ?? MOUNT_TIME;
  const [elapsed, setElapsed] = useState(Date.now() - start);
  useEffect(() => {
    const id = setInterval(() => setElapsed(Date.now() - start), 1000);
    return () => clearInterval(id);
  }, [start]);
  return (
    <span style={{ fontFamily: "monospace", fontSize: "11px", color, letterSpacing: "0.08em" }}>
      {format(elapsed)}
    </span>
  );
}

// packages/vue/src/components/Uptime.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{ startMs?: number; color?: string }>(), { color: "var(--fg)" });
const mountTime = Date.now();
const elapsed = ref(0);
let id: ReturnType<typeof setInterval> | null = null;
onMounted(() => {
  const start = props.startMs ?? mountTime;
  id = setInterval(() => { elapsed.value = Date.now() - start; }, 1000);
});
onUnmounted(() => { if (id) clearInterval(id); });

const format = (ms: number) => {
  const s = Math.floor(ms / 1000);
  const d = Math.floor(s / 86400), h = Math.floor((s % 86400) / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60;
  return [d, h, m, sec].map(v => String(v).padStart(2, "0")).join(":");
};
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color, letterSpacing: '0.08em' }">
    {{ format(elapsed) }}
  </span>
</template>
