// packages/svelte/src/components/Uptime.svelte
<script lang="ts">
let { startMs = undefined as number | undefined, color = "var(--fg)" } = $props();
const mount = Date.now();
let elapsed = $state(0);
$effect(() => {
  const start = startMs ?? mount;
  const id = setInterval(() => { elapsed = Date.now() - start; }, 1000);
  return () => clearInterval(id);
});
function fmt(ms: number) {
  const s = Math.floor(ms/1000), d=Math.floor(s/86400), h=Math.floor((s%86400)/3600), m=Math.floor((s%3600)/60), sec=s%60;
  return [d,h,m,sec].map(v=>String(v).padStart(2,"0")).join(":");
}
</script>
<span style="font-family:monospace; font-size:11px; color:{color}; letter-spacing:0.08em">{fmt(elapsed)}</span>

// packages/vue/src/components/Uptime.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const props = withDefaults(defineProps<{ startMs?: number; color?: string }>(), { color: "var(--fg)" });
const mountTime = Date.now();
const elapsed = ref(0);
let id: ReturnType<typeof setInterval> | null = null;
onMounted(() => {
  const start = props.startMs ?? mountTime;
  id = setInterval(() => { elapsed.value = Date.now() - start; }, 1000);
});
onUnmounted(() => { if (id) clearInterval(id); });

const format = (ms: number) => {
  const s = Math.floor(ms / 1000);
  const d = Math.floor(s / 86400), h = Math.floor((s % 86400) / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60;
  return [d, h, m, sec].map(v => String(v).padStart(2, "0")).join(":");
};
</script>
<template>
  <span :style="{ fontFamily: 'monospace', fontSize: '11px', color: props.color, letterSpacing: '0.08em' }">
    {{ format(elapsed) }}
  </span>
</template>
