// packages/svelte/src/components/VUMeter.svelte
<script lang="ts">
import { createTicker } from "@micrographics/core";
let { color = "var(--accent)", speed = 80, height = 40 } = $props();
let levels = $state([0.7, 0.5]);
$effect(() => {
  return createTicker(speed, () => {
    levels = levels.map(v => Math.max(0.05, Math.min(1, v + (Math.random() - 0.5) * 0.25)));
  });
});
const segments = 8;
const barW = 8;
const gap = 2;
const svgW = $derived(2 * barW + gap + 4);
const segH = $derived(Math.floor(height / segments) - 1);
</script>
<svg width={svgW} {height} style="display:block" shape-rendering="crispEdges">
  {#each levels as lv, col}
    {@const filled = Math.round(lv * segments)}
    {#each Array.from({ length: segments }, (_, i) => i) as i}
      {@const seg = segments - 1 - i}
      {@const x = col * (barW + gap + 2)}
      {@const y = i * (segH + 1)}
      {@const active = seg < filled}
      {@const segColor = seg >= segments - 2 ? "var(--accent-red)" : seg >= segments - 4 ? "var(--accent-amber)" : color}
      <rect {x} {y} width={barW} height={segH} fill={active ? segColor : "var(--fg-dimmer)"} opacity={active ? 1 : 0.2} />
    {/each}
  {/each}
</svg>

// packages/vue/src/components/VUMeter.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { createTicker } from "@micrographics/core";

const props = withDefaults(defineProps<{ color?: string; speed?: number; height?: number }>(),
  { color: "var(--accent)", speed: 80, height: 40 });

const levels = ref([0.7, 0.5]);
let cleanup: (() => void) | null = null;
onMounted(() => {
  cleanup = createTicker(props.speed, () => {
    levels.value = levels.value.map(v => Math.max(0.05, Math.min(1, v + (Math.random() - 0.5) * 0.25)));
  });
});
onUnmounted(() => cleanup?.());
const segments = 8;
const segH = () => Math.floor(props.height / segments) - 1;
const segColor = (col: number, i: number) => {
  const seg = segments - 1 - i;
  if (seg >= segments - 2) return "var(--accent-red)";
  if (seg >= segments - 4) return "var(--accent-amber)";
  return props.color;
};
const filled = (col: number) => Math.round(levels.value[col] * segments);
</script>
<template>
  <svg :width="20" :height="height" style="display:block" shape-rendering="crispEdges">
    <template v-for="col in 2" :key="col">
      <rect v-for="i in segments" :key="`${col}-${i}`"
        :x="(col-1) * 11" :y="(i-1) * (segH() + 1)"
        width="8" :height="segH()"
        :fill="(segments - i) < filled(col-1) ? segColor(col-1, i-1) : 'var(--fg-dimmer)'"
        :opacity="(segments - i) < filled(col-1) ? 1 : 0.2"
      />
    </template>
  </svg>
</template>
